### ISSUE TITLE
site URL is not working

### ISSUE THREAD

**Issue by AshishkrGoyal** [fossasia/opentechsummit.cn#1]
site is not opening while clicking on the given URL:

http://opentechsummit.cn/

**Comment by ms10398** [comment]
It is working for me please check it.
Screenshot
![screenshot from 2017-09-23 20-41-13](https://user-images.githubusercontent.com/26259547/30774414-ba192b5a-a09f-11e7-82d2-dcf78f0c6789.png)

**Comment by mariobehling** [comment]
CNAME was added recently. Cheers.
