### ISSUE TITLE
I want to use this as a template.

### ISSUE THREAD

**Issue by giantthinker** [fossasia/opentechsummit.cn#14]
Hello, please can you provide a documentation on how I can get started with this as a template?
Thanks.

**Comment by tabesin** [comment]
What do you mean by "this"? 

Do you want to fork the repo and create your own web site or template for a website?

**Comment by giantthinker** [comment]
Yeah that's what I want to do. 
Thanks.

**Comment by mariobehling** [comment]
This issue is invalid.

**Comment by giantthinker** [comment]
sorry @mariobehling can you please provide me with a documentation to use fork and use this website?
Thanks.

**Comment by tabesin** [comment]
The Clone button is available on github. It is important that you change the CNAME file accordingly, so you don't cause us any trouble with the site. If you need any consultancy I am sure we could get you developers who help for a competitive price. You may also want to join the fossasia channels at gitter.im. Of course you are expected to respect the license and remove Fossasia branded IP. Happy Hacking!

**Comment by giantthinker** [comment]
Thank you so much for the info. I'll handle it. I thought I needed some extra setup. 
I'm so grateful.
