### ISSUE TITLE
Update location for  Open Tech Summit China

### ISSUE THREAD

**Issue by edenyay** [fossasia/opentechsummit.cn#18]
Replace the current location with the following and include the map link

Chinese: 深圳市南山区 西丽大学城 清华大学深圳研究生院 C2 三楼 大报告厅

English: OpenFIESTA, 3rd floor, Building C2, Tsinghua Campus in the University Town, Shenzhen

**Comment by kayyjayy007** [comment]
I want to take on this issue.
