### ISSUE TITLE
Fix UI input box color

### ISSUE THREAD

**Issue by ms10398** [fossasia/opentechsummit.cn#2]
I think for input of subscription some dark color would be better as white is not properly visible
@mariobehling 
![screenshot from 2017-09-23 20-43-53](https://user-images.githubusercontent.com/26259547/30774441-2f7fbc2e-a0a0-11e7-8aae-24ac1e74bb71.png)

Yes I would like to work on it!

**Comment by mariobehling** [comment]
Lead design is on fossasia.org. We follow that. Would be great, if you could help with SUSI.AI projects in FOSSASIA. Cheers!
